version: 0.8.3.{build}

environment:
  matrix:
  - PlatformToolset: v142
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

  - PlatformToolset: v143
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022


platform:
    - x64
    - Win32

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%platform%"=="Win32" set archi=x86
    - if "%platform%"=="Win32" set platform_input=Win32

    - if "%PlatformToolset%"=="v141_xp" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%
    - if "%PlatformToolset%"=="v142"    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%
    - if "%PlatformToolset%"=="v143"    call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"\NppExec
    - msbuild NppExec_VC2015.sln /m /p:configuration="%configuration%" /p:platform="%platform_input%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - cd "%APPVEYOR_BUILD_FOLDER%"\NppExecPluginMsgTester
    - msbuild NppExecPluginMsgTester_VC2015.sln /m /p:configuration="%configuration%" /p:platform="%platform_input%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:

    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-

        if ($env:PLATFORM_INPUT -eq "x64") {
            Push-AppveyorArtifact "NppExec\$env:PLATFORM_INPUT\$env:CONFIGURATION\NppExec.dll" -FileName NppExec.dll
        }

        if ($env:PLATFORM_INPUT -eq "Win32" ) {
            Push-AppveyorArtifact "NppExec\$env:CONFIGURATION\NppExec.dll" -FileName NppExec.dll
        }

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "v143") {
            if($env:PLATFORM_INPUT -eq "x64"){
                $ZipFileName = "NppExec_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
                7z a $ZipFileName $env:APPVEYOR_BUILD_FOLDER\NppExec\$env:PLATFORM_INPUT\$env:CONFIGURATION\*.dll
                Push-AppveyorArtifact $ZipFileName -FileName $ZipFileName
            }
            if($env:PLATFORM_INPUT -eq "Win32"){
                $ZipFileName = "NppExec_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
                7z a $ZipFileName $env:APPVEYOR_BUILD_FOLDER\NppExec\$env:CONFIGURATION\*.dll
                Push-AppveyorArtifact $ZipFileName -FileName $ZipFileName
            }
        }

artifacts:
    - path: NppExec_*.zip
      name: releases
